name: branch-name

on:
  pull_request:
    branches: [develop, main]
    types: [opened, synchronize, reopened, edited]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name
        run: |
          BRANCH="${{ github.head_ref }}"
          REGEX='^(feat|fix|hotfix|refactor|chore|docs|test|ci|infra|perf)\/(gh-[0-9]+|no-issue)-[a-z0-9]+(-[a-z0-9]+)*$|^release\/v[0-9]+\.[0-9]+\.[0-9]+$'
          echo "Branch: $BRANCH"
          if [[ ! "$BRANCH" =~ $REGEX ]]; then
            echo "Invalid branch name."
            exit 1
          fi